# build it

name: Build and Test Coalesce App

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run .NET Tests
        run: dotnet test --logger trx

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            TestResults/**/*.trx
                    
      # - name: Test Summary
      #   uses: test-summary/action@v2
      #   with:
      #     paths: "test/**/*.trx"
      #     output: test-summary.md
      #   if: always()      

      # - name: Upload test summary
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: test-summary
      #     path: test-summary.md
      #   if: always()        

      # for now, we're just building to check it, not to deploy
      # - name: dotnet publish
      #   run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/app

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: .net-app
      #     path: ${{env.DOTNET_ROOT}}/app
