# build it

name: Build and Test Coalesce App

on:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.x"
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Run .NET Tests
        run: dotnet test

      # for now, we're just building to check it, not to deploy
      # - name: dotnet publish
      #   run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/app

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: .net-app
      #     path: ${{env.DOTNET_ROOT}}/app
