# build it

name: Build and Test Coalesce App

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with dotnet
        run: dotnet build --configuration Release
        
      - name: Set up node with caching
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./widgetmaker.Web/package-lock.json

      - name: Restore and Install npm Packages
        run: |
          rm package-lock.json
          npm i
        working-directory: "./widgetmaker.Web"
        shell: pwsh

      - name: Run npm Build
        run: npm run build
        working-directory: "./widgetmaker.Web"
        shell: pwsh
        
      - name: Run .NET Tests
        run: dotnet test --logger trx

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/TestResults/*.trx

