name: test summary

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Restore and Install npm Packages
        run: |
            $env:GITHUB_STEP_SUMMARY = "### message 1"
            "### message 2" >> $GITHUB_STEP_SUMMARY
            "### message 3" >> results.md
        shell: pwsh
        
      - name: set the summary
        run: cat results.md >> $GITHUB_STEP_SUMMARY
        shell: bash